### ISSUE TITLE
BUILD: summary detail

### ISSUE THREAD

**Issue by komalgill0310** [chingu-voyages/v46-tier2-team-20#22]

**Comment by nghia-nguyen-dev** [comment]
Please also create a Background blur component to accompany this. Its a small component so i didn't want to split it out into a new task

**Comment by allison-truhlar** [comment]
@nghia-nguyen-dev Could you please elaborate on what the background blur component is and when it should appear? I see it in the Figma file, but it just looks like a grey rectangle.

**Comment by nghia-nguyen-dev** [comment]
@allison-truhlar Its just basically a div that darkens + blurs the underlying content. It should appear with the Summary Detail component. In terms of building it out, it might be best to have it as a separate small component or you can nest it inside of the Summary Detail if that is better??If this is something that might take a lot of time to implement then I could create a separate ticket and list it as low priority/ nice to have

**Comment by allison-truhlar** [comment]
@nghia-nguyen-dev Thanks for the extra info! I'll think about it and see if it makes sense to implement this in the Summary Detail component or a separate component!
