### ISSUE TITLE
Pass data from the RecipesBrief component to the RecipeDetails (aka summary detail) component

### ISSUE THREAD

**Issue by allison-truhlar** [chingu-voyages/v46-tier2-team-20#46]
Pass props from each recipe card created in RecipesBrief down to the detailed recipe display.

**Comment by komalgill0310** [comment]
I believe @allison-truhlar has done this part already, so I am closing this issue.

**Comment by komalgill0310** [comment]
it was done by @allison-truhlar, so I am moving this task to under "Done" column. As it is already under review of "Build: summary detail"
