### ISSUE TITLE
Refactor event handler functions in App.jsx

### ISSUE THREAD

**Issue by AOA19** [chingu-voyages/v46-tier2-team-20#65]
Move the three event handler functions from App.jsx to a separate file (Custom Hook). Refer to this [comment ](https://github.com/chingu-voyages/v46-tier2-team-20/pull/62#issuecomment-1804713811) from issue #61

**Comment by allison-truhlar** [comment]
@AOA19 - ignore my last comment in issue #62 - thanks for opening this issue!
